# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12wiV9PRYFfakn2Q7nAXybpIN0BlsdeCa
"""

def make_student(name, scores):
    average = sum(scores) / len(scores)
    return {"name": name, "scores": scores, "average": average}

def class_summary(students):
    top_student = None
    highest_avg = 0
    for s in students:
        if s["average"] > highest_avg:
            highest_avg = s["average"]
            top_student = s["name"]
    return top_student

student1 = make_student("agie", [90, 85, 88])
student2 = make_student(name="jordan", scores=[70, 95, 80])
student3 = make_student("nizar", [100, 92, 96])

classroom = [student1, student2, student3]

top = class_summary(classroom)
print("The top student is:", top)